{{- define "openstack-cluster.controlplane.kubeadmConfigSpec.kubeProxyConfiguration" -}}
{{- with .kubeProxyConfiguration }}
files:
  - path: /run/kubeadm/kube-proxy-configuration.yaml
    content: |
      ---
      apiVersion: kubeproxy.config.k8s.io/v1alpha1
      kind: KubeProxyConfiguration
      {{- toYaml . | nindent 6 }}
    owner: root:root
    permissions: "0644"
preKubeadmCommands:
  - cat /run/kubeadm/kube-proxy-configuration.yaml >> /run/kubeadm/kubeadm.yaml
{{- end }}
{{- end }}

{{- define "openstack-cluster.controlplane.kubeadmConfigSpec" -}}
{{-
  $baseKubeadmConfigSpec :=
    include
      "openstack-cluster.kubeadmConfigSpec"
      (list . .Values.controlPlane.kubeadmConfigSpec) |
    fromYaml
}}
{{-
  $kubeProxyConfigOverrides :=
    include
      "openstack-cluster.controlplane.kubeadmConfigSpec.kubeProxyConfiguration"
      .Values.controlPlane.kubeadmConfigSpec |
    fromYaml
}}
{{-
  $mergedKubeadmConfigSpec :=
    include
      "openstack-cluster.mergeConcat"
      (list $baseKubeadmConfigSpec $kubeProxyConfigOverrides) |
    fromYaml
}}
{{- omit $mergedKubeadmConfigSpec "kubeProxyConfiguration" | toYaml }}
{{- end }}

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
  annotations:
    # We let Cluster API clean up the control plane resource
    # Deleting it ourselves, which CAPI is not expecting, can cause some nasty race conditions
    helm.sh/resource-policy: keep
    # NOTE: Argo won't delete this object itself as it has an owner reference to the cluster
spec:
  version: v{{ .Values.controlPlane.kubernetesVersion | default .Values.kubernetesVersion | required "One of .Values.controlPlane.kubernetesVersion or .Values.kubernetesVersion is required" | trimPrefix "v" }}
  replicas: {{ .Values.controlPlane.machineCount }}
  rolloutStrategy: {{ toYaml .Values.controlPlane.rolloutStrategy | nindent 4 }}
  machineTemplate:
    metadata:
      labels: {{ include "openstack-cluster.componentSelectorLabels" (list . "control-plane") | nindent 8 }}
    infrastructureRef:
      kind: OpenStackMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      name: {{ include "openstack-cluster.controlplane.mt.name" . }}
      namespace: {{ .Release.Namespace }}
    nodeDrainTimeout: {{ .Values.controlPlane.nodeDrainTimeout }}
    nodeVolumeDetachTimeout: {{ .Values.controlPlane.nodeVolumeDetachTimeout }}
    nodeDeletionTimeout: {{ .Values.controlPlane.nodeDeletionTimeout }}
  kubeadmConfigSpec: {{ include "openstack-cluster.controlplane.kubeadmConfigSpec" . | nindent 4 }}
