{{- if .Values.controlPlane.healthCheck.enabled }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
  annotations:
    # Argo should manage this resource even though it has an owner ref for the cluster
    argocd.argoproj.io/managed-resource: "true"
spec:
  clusterName: {{ include "openstack-cluster.clusterName" . }}
  selector:
    matchLabels: {{ include "openstack-cluster.componentSelectorLabels" (list . "control-plane") | nindent 6 }}
  {{- toYaml .Values.controlPlane.healthCheck.spec | nindent 2 }}
{{- end }}
