---
kubernetesVersion: 1.23.16

# ubuntu-focal-kube-v1.23.16-230411-1334
machineImageId: 39c82d94-94af-423f-8aa0-f4cb8e9cb0d1

apiServer:
  enableLoadBalancer: false

controlPlane:
  machineFlavor: vm.ska.cpu.general.small
  machineCount: 1

nodeGroups:
  - machineCount: 2
    machineFlavor: vm.ska.cpu.general.small
    name: test-group1
