---
kubernetesVersion: 1.23.9

machineImageId: c2f235c1-ad10-4e96-8568-aac864945686

controlPlane:
  machineFlavor: vm.alaska.cpu.general.small
  machineCount: 1

nodeGroups:
  - machineCount: 2
    machineFlavor: vm.alaska.cpu.general.small
    name: test-group1
