---
kubernetesVersion: 1.24.12

# ubuntu-focal-kube-v1.24.12-230411-1402
machineImageId: 3b7ad1a9-6968-4a00-bfc4-fe5378bfef7b

controlPlane:
  machineFlavor: vm.ska.cpu.general.small
  machineCount: 1

nodeGroups:
  - machineCount: 2
    machineFlavor: vm.ska.cpu.general.small
    name: test-group1
