---
kubernetesVersion: 1.26.0

machineImageId: 5eae91aa-0c96-472e-ba8c-edd6162281f7

controlPlane:
  machineFlavor: vm.ska.cpu.general.small
  machineCount: 1

nodeGroups:
  - machineCount: 2
    machineFlavor: vm.ska.cpu.general.small
    name: test-group1
