---
kubernetesVersion: 1.26.3

# ubuntu-focal-kube-v1.26.3-230411-1504
machineImageId: 5a3c11ce-32a0-47f5-8166-7ad0f8477b73

controlPlane:
  machineFlavor: vm.ska.cpu.general.small
  machineCount: 1

nodeGroups:
  - machineCount: 2
    machineFlavor: vm.ska.cpu.general.small
    name: test-group1
