# Content for an OpenStack clouds.yaml file
# Having this as a top-level item allows a clouds.yaml file from OpenStack to be used as a values file
clouds:
# The name of the cloud to use from the specified clouds
cloudName: openstack

jobImage:
  repository: ghcr.io/stackhpc/k8s-utils
  tag: # defaults to chart appVersion
  pullPolicy: IfNotPresent

# Nameservers to use for bootstrap jobs that are not using host networking
# but must execute before the cluster DNS is ready
bootstrapDNSNameservers:
  - 8.8.8.8
  - 8.8.4.4

# The tolerations to use for jobs that are part of bootstrapping the cluster
# e.g. CNI, external cloud provider
bootstrapTolerations:
  # Allow the job to run on a control plane node if required
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  # Allow the job to run on a node awaiting initialisation by an external cloud provider
  - key: node.cloudprovider.kubernetes.io/uninitialized
    operator: Equal
    value: "true"
    effect: NoSchedule
  # Allow the job to run on nodes that are not ready
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoSchedule

# Settings for the CNI addon
cni:
  # Indicates if a CNI should be deployed
  enabled: true
  # The type of CNI to deploy - support values are calico, weave
  type: calico
  # Settings for the calico CNI
  calico:
    # The version of Calico to deploy
    # This is only used in the default manifest URL
    version: v3.20
    # The URL of the Calico manifest
    # This is treated as a template during rendering
    manifestURL: https://docs.projectcalico.org/{{ .Values.cni.calico.version }}/manifests/calico.yaml
  # Settings for the Weave CNI
  weave:
    # The base URL of the Weave manifest
    # The output of "kubectl version" is added as a query parameter, as per the docs
    manifestURL: https://cloud.weave.works/k8s/net

# Settings for the cloud controller manager for external cloud providers
ccm:
  # Indicates if an external cloud controller manager should be deployed
  enabled: true
  # The type of the external CCM to deploy - currently only OpenStack is supported
  type: openstack
  # Settings for the OpenStack cloud controller manager
  openstack:
    # The version of the OpenStack CCM to install
    # This is treated as a template during rendering
    version: release-{{ .Capabilities.KubeVersion.Major }}.{{ .Capabilities.KubeVersion.Minor }}
    # The base URL for OpenStack CCM manifests
    # This is treated as a template during rendering
    manifestsBaseURL: https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/{{ tpl .Values.ccm.openstack.version . }}
    # The prefix for CCM manifests
    ccmManifestsPrefix: /manifests/controller-manager
    # The prefix for RBAC manifests
    # Unfortunately, this changes for different Kubernetes versions
    # This is treated as a template during rendering
    rbacManifestsPrefix: "{{ ternary \"/manifests/controller-manager\" \"/cluster/addons/rbac\" (semverCompare \">=1.22\" .Capabilities.KubeVersion.Version) }}"
    # The URLs to use for the manifests
    # These are treated as templates during rendering
    manifests:
      roles: "{{ tpl .Values.ccm.openstack.manifestsBaseURL . }}{{ tpl .Values.ccm.openstack.rbacManifestsPrefix . }}/cloud-controller-manager-roles.yaml"
      roleBindings: "{{ tpl .Values.ccm.openstack.manifestsBaseURL . }}{{ tpl .Values.ccm.openstack.rbacManifestsPrefix . }}/cloud-controller-manager-role-bindings.yaml"
      daemonset: "{{ tpl .Values.ccm.openstack.manifestsBaseURL . }}{{ tpl .Values.ccm.openstack.ccmManifestsPrefix . }}/openstack-cloud-controller-manager-ds.yaml"
    # cloud-config options for the cloud controller manager
    # The [Global] section is configured to use the specified cloud from .Values.clouds
    # See https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager
    cloudConfig:
      networking:
      loadBalancer:
      metadata:

# Settings for the NVIDIA GPU operator
nvidiaGPUOperator:
  # Indicates if the NVIDIA GPU operator should be enabled
  enabled: true
  chart:
    repo: https://nvidia.github.io/gpu-operator
    name: gpu-operator
    version: v1.8.1
  release:
    namespace: gpu-operator
    name: gpu-operator
    timeout: 5m
  values:
    # By default, CAPI clusters use containerd
    operator:
      defaultRuntime: containerd
