# Content for an OpenStack clouds.yaml file
# Having this as a top-level item allows a clouds.yaml file from OpenStack to be used as a values file
clouds:
# The name of the cloud to use from the specified clouds
cloudName: openstack
# The PEM-encoded CA certificate for the specified cloud
cloudCACert:

jobImage:
  repository: ghcr.io/stackhpc/k8s-utils
  tag: # defaults to chart appVersion
  pullPolicy: IfNotPresent

# Indicates whether to install bootstrap charts only
# If this is set to true, then only the CNI and CCM will be installed
bootstrapOnly: false

# Nameservers to use for bootstrap jobs that are not using host networking
# but must execute before the cluster DNS is ready
bootstrapDNSNameservers:
  - 8.8.8.8
  - 8.8.4.4

# The tolerations to use for jobs that are part of bootstrapping the cluster
# e.g. CNI, external cloud provider
bootstrapTolerations:
  # Allow the job to run on a control plane node if required
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  # Allow the job to run on a node awaiting initialisation by an external cloud provider
  - key: node.cloudprovider.kubernetes.io/uninitialized
    operator: Equal
    value: "true"
    effect: NoSchedule
  # Allow the job to run on nodes that are not ready
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoSchedule

# Settings for the CNI addon
cni:
  # Indicates if a CNI should be deployed
  enabled: true
  # The type of CNI to deploy - support values are calico, weave
  type: calico
  # Settings for the calico CNI
  calico:
    # The version of Calico to deploy
    # This is only used in the default manifest URL
    version: v3.20
    # The URL of the Calico manifest
    # This is treated as a template during rendering
    manifestURL: https://docs.projectcalico.org/{{ .Values.cni.calico.version }}/manifests/calico.yaml
    # Any kustomization to be applied to the Calico manifests
    kustomization:
  # Settings for the Weave CNI
  weave:
    # The base URL of the Weave manifests
    # There is one manifest for Kubernetes >= 1.16 and one for the rest
    version: "{{ ternary \"v1.16\" \"v1.13\" (semverCompare \">=1.16\" .Capabilities.KubeVersion.Version) }}"
    manifestURL: https://cloud.weave.works/k8s/{{ tpl .Values.cni.weave.version . }}/net
    # Any kustomization to be applied to the Weave manifests
    kustomization:

# Settings for the OpenStack integrations
openstack:
  # Indicates if the OpenStack integrations should be enabled
  enabled: false
  # The version of the OpenStack cloud provider to install
  # By default, use the release branch for the Kubernetes version of the target cluster
  version: release-{{ .Capabilities.KubeVersion.Major }}.{{ .Capabilities.KubeVersion.Minor }}
  # The base URL for OpenStack cloud provider manifests
  # By default, pull the manifests from GitHub
  manifestsBaseURL: https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/{{ tpl .Values.openstack.version . }}
  # cloud-config options for the OpenStack integrations
  # The [Global] section is configured to use the specified cloud from .Values.clouds
  # See https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager
  # and https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#block-storage
  cloudConfig:
    networking:
    loadBalancer:
    blockStorage:
    metadata:
  # Settings for the Cloud Controller Manager (CCM)
  ccm:
    # Indicates if the OpenStack CCM should be enabled
    # By default, the CCM is enabled if the OpenStack integrations are enabled
    enabled: true
    # The prefix for RBAC manifests
    # Unfortunately, this changes for different Kubernetes versions
    rbacManifestsPrefix: "{{ ternary \"/manifests/controller-manager\" \"/cluster/addons/rbac\" (semverCompare \">=1.22\" .Capabilities.KubeVersion.Version) }}"
    # The URLs to use for the manifests
    manifests:
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}{{ tpl .Values.openstack.ccm.rbacManifestsPrefix . }}/cloud-controller-manager-roles.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}{{ tpl .Values.openstack.ccm.rbacManifestsPrefix . }}/cloud-controller-manager-role-bindings.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml"
    # Any kustomization to apply to the OpenStack CCM manifests
    kustomization:
  # Settings for the Cinder CSI plugin
  csiCinder:
    # Indicates if the Cinder CSI should be enabled
    # By default, it is enabled if the OpenStack integrations are enabled
    enabled: true
    # The URLs to use for the manifests
    manifests:
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml"
      - "{{ tpl .Values.openstack.manifestsBaseURL . }}/manifests/cinder-csi-plugin/csi-cinder-driver.yaml"
    # Any kustomization to apply to the OpenStack CCM manifests
    kustomization:
    # Variables affecting the definition of the storage class
    storageClass:
      # Indicates if the storage class should be enabled
      enabled: true
      # The name of the storage class
      name: csi-cinder
      # Indicates if the storage class should be annotated as the default storage class
      isDefault: true
      # The reclaim policy for the storage class
      reclaimPolicy: Delete
      # Indicates if volume expansion is allowed
      allowVolumeExpansion: true

# Settings for cert-manager
certManager:
  # Indicates if cert-manager should be enabled
  enabled: true
  chart:
    repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.5.3
  release:
    namespace: cert-manager
    name: cert-manager
    timeout: 5m
  # See https://cert-manager.io/docs/installation/helm/ for available values
  values:
    # By default, make sure the cert-manager CRDs are installed
    installCRDs: true
    # Disable Prometheus support for now
    prometheus:
      enabled: false

# Settings for the NVIDIA GPU operator
nvidiaGPUOperator:
  # Indicates if the NVIDIA GPU operator should be enabled
  enabled: false
  chart:
    repo: https://nvidia.github.io/gpu-operator
    name: gpu-operator
    version: v1.8.1
  release:
    namespace: gpu-operator
    name: gpu-operator
    timeout: 5m
  values:
    # By default, CAPI clusters use containerd
    operator:
      defaultRuntime: containerd

# Custom manifests to apply
# This should be a map of filenames to manifest content
customManifests:

# Custom Helm releases to apply
# This should be a map of release name to release parameters
customHelmReleases:
  # my-wordpress:
  #   chart:
  #     # The repository that the chart is in
  #     repo: https://charts.bitnami.com/bitnami
  #     # The name of the chart
  #     name: wordpress
  #     # The version of the chart to install
  #     # NOTE: THIS IS REQUIRED
  #     version: 12.1.6
  #   # The namespace for the release
  #   # If not given, this defaults to the release name
  #   namespace: my-wordpress
  #   # The amount of time to wait for the chart to install before rolling back
  #   timeout: 5m
  #   # The values for the chart
  #   values:
