{{- if and .Values.cni.enabled (eq .Values.cni.type "weave") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "cni-weave-kustomize") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "cni-weave") | nindent 4 }}
stringData:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
    - {{ tpl .Values.cni.weave.manifestURL . }}
    {{- with .Values.cni.weave.kustomization }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
