---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
spec:
  template:
    spec:
      identityRef:
        kind: Secret
        name: {{ include "openstack-cluster.componentName" (list . "cloud-config") }}
      cloudName: {{ .Values.cloudName }}
      image: {{ .Values.machineImage | required ".Values.machineImage is required" }}
      flavor: {{ .Values.controlPlane.machineFlavor | required ".Values.controlPlane.machineFlavor is required" }}
      sshKeyName: {{ .Values.machineSSHKeyName | required ".Values.machineSSHKeyName is required" }}
