{{-
  if and
    .Values.addons.enabled
    .Values.addons.openstack.enabled
    .Values.addons.openstack.csiCinder.enabled
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "csi-cinder") }}-config
  labels:
    {{- include "openstack-cluster.componentLabels" (list . "csi-cinder") | nindent 4 }}
    {{ .Values.addons.watchLabel }}: ""
stringData:
  # By default, we disable the storage class deployed by the cinder-csi chart
  # We deploy our own instead as it gives us more control over the parameters
  defaults: |
    secret:
      enabled: true
      create: false
      name: cloud-config
    csi:
      plugin:
        # This has to be non-empty or the chart fails to render
        volumes:
          - name: cacert
            emptyDir: {}
        volumeMounts:
          - name: cloud-config
            mountPath: /etc/config
            readOnly: true
          - name: cloud-config
            mountPath: /etc/kubernetes
            readOnly: true
    storageClass:
      enabled: false
    clusterID: {{ include "openstack-cluster.clusterName" . }}
  overrides: |
    {{- toYaml .Values.addons.openstack.csiCinder.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "csi-cinder") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "csi-cinder") | nindent 4 }}
spec:
  clusterName: {{ include "openstack-cluster.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.addons.openstack.csiCinder.chart | nindent 4 }}
  targetNamespace: {{ .Values.addons.openstack.targetNamespace }}
  releaseName: csi-cinder
  valuesSources:
    - secret:
        name: {{ include "openstack-cluster.componentName" (list . "csi-cinder") }}-config
        key: defaults
    - secret:
        name: {{ include "openstack-cluster.componentName" (list . "csi-cinder") }}-config
        key: overrides
{{- if .Values.addons.openstack.csiCinder.storageClass.enabled }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "csi-cinder") }}-storageclass
  labels: {{ include "openstack-cluster.componentLabels" (list . "csi-cinder") | nindent 4 }}
spec:
  clusterName: {{ include "openstack-cluster.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.addons.openstack.targetNamespace }}
  releaseName: csi-cinder-storageclass
  manifestSources:
    - template: |
        {{- with .Values.addons.openstack.csiCinder.storageClass }}
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: {{ .name }}
          {{- if .isDefault }}
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          {{- end }}
        provisioner: cinder.csi.openstack.org
        parameters:
          availability: {{ .availabilityZone }}
          {{- with .volumeType }}
          type: {{ . }}
          {{- end }}
        reclaimPolicy: {{ .reclaimPolicy }}
        allowVolumeExpansion: {{ .allowVolumeExpansion }}
        volumeBindingMode: WaitForFirstConsumer
        {{- with .allowedTopologies }}
        allowedTopologies: {{ toYaml . | nindent 6 }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
