{{- if and .Values.ccm.enabled (eq .Values.ccm.type "openstack") }}
apiVersion: v1
kind: Secret
metadata:
  # This must match the name and namespace expected by the manifests
  name: cloud-config
  namespace: kube-system
  labels: {{ include "cluster-addons.componentLabels" (list . "ccm-openstack") | nindent 4 }}
  # The addons helm release might be deleted without deleting the OpenStack CCM
  # So leave this behind in order for the CCM to continue functioning
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  cloud.conf: |
    {{- .Values.ccm.openstack.cloudConfig | nindent 4 }}
{{- end }}
