{{- if and .Values.ccm.enabled (eq .Values.ccm.type "openstack") }}
apiVersion: v1
kind: Secret
metadata:
  # This must match the name and namespace expected by the manifests
  name: cloud-config
  namespace: kube-system
  labels: {{ include "cluster-addons.componentLabels" (list . "ccm-openstack") | nindent 4 }}
  # The addons helm release might be deleted without deleting the OpenStack CCM
  # So leave this behind in order for the CCM to continue functioning
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  # Just include the data for the cloud we will be using
  clouds.yaml: |
    clouds:
      openstack:
        {{ index .Values.clouds .Values.cloudName | toYaml | indent 8 | trim }}
  # In the cloud.conf, reference the clouds.yaml for authentication params
  cloud.conf: |
    [Global]
    use-clouds=true
    clouds-file=/etc/config/clouds.yaml
    cloud=openstack

    {{- with .Values.ccm.openstack.cloudConfig.networking }}
    [Networking]
    {{- range $item, $value := . }}
    $item=$value
    {{- end }}
    {{- end }}

    {{- with .Values.ccm.openstack.cloudConfig.loadBalancer }}
    [LoadBalancer]
    {{- range $item, $value := . }}
    $item=$value
    {{- end }}
    {{- end }}

    {{- with .Values.ccm.openstack.cloudConfig.metadata }}
    [Metadata]
    {{- range $item, $value := . }}
    $item=$value
    {{- end }}
    {{- end }}
{{- end }}
