{{- if and .Values.ccm.enabled (eq .Values.ccm.type "openstack") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "ccm-openstack-kustomize") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "ccm-openstack") | nindent 4 }}
stringData:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
    - {{ tpl .Values.ccm.openstack.manifests.roles . }}
    - {{ tpl .Values.ccm.openstack.manifests.roleBindings . }}
    - {{ tpl .Values.ccm.openstack.manifests.daemonset . }}
    {{- with .Values.ccm.openstack.kustomization }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
