{{- if and .Values.serviceAccount.create .Values.kubeconfigSecret.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "addon.fullname" . }}-manage-jobs
  labels: {{ include "addon.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - get
      - patch
{{- end }}
