apiVersion: v1
kind: Secret
metadata:
  name: {{ include "addon.fullname" . }}-config
  labels: {{ include "addon.labels" . | nindent 4 }}
stringData:
  {{- range $filename, $content := .Values.extraFiles }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- with .Values.hooks.preInstall }}
  hook-preinstall.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.hooks.postInstall }}
  hook-postinstall.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.hooks.preDelete }}
  hook-predelete.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.hooks.postDelete }}
  hook-postdelete.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- if eq .Values.installType "helm" }}
  values.yaml: |
    {{- include "addon.helm.values" . | nindent 4 }}
  install.sh: |
    {{- include "addon.helm.install" . | nindent 4 }}
  delete.sh: |
    {{- include "addon.helm.delete" . | nindent 4 }}
  {{- else if eq .Values.installType "kustomize" }}
  kustomization.yaml: |
    {{- include "addon.kustomize.kustomization" . | nindent 4 }}
  install.sh: |
    {{- include "addon.kustomize.install" . | nindent 4 }}
  delete.sh: |
    {{- include "addon.kustomize.delete" . | nindent 4 }}
  {{- else if eq .Values.installType "custom" }}
  install.sh: |
    {{-
      tpl (required ".Values.custom.install is required for a custom job" .Values.custom.install) . |
        nindent 4
    }}
  delete.sh: |
    {{-
      tpl (required ".Values.custom.delete is required for a custom job" .Values.custom.delete) . |
        nindent 4
    }}
  {{- else }}
  {{- fail (printf "Unrecognised install type '%s'" .Values.installType) }}
  {{- end }}
