{{- if and (not .Values.bootstrapOnly) .Values.openstack.enabled .Values.openstack.csiCinder.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cinder-kustomize") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "csi-cinder") | nindent 4 }}
stringData:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
    {{- range $manifestTemplate := .Values.openstack.csiCinder.manifests }}
    - {{ tpl $manifestTemplate $ }}
    {{- end }}
    {{- if .Values.openstack.csiCinder.storageClass.enabled }}
    - ./storageclass.yaml
    {{- end }}
    {{- with .Values.openstack.csiCinder.kustomization }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.openstack.csiCinder.storageClass }}
  {{- if .enabled }}
  storageclass.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: {{ .name }}
      {{- if .isDefault }}
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      {{- end }}
    provisioner: cinder.csi.openstack.org
    reclaimPolicy: {{ .reclaimPolicy }}
    allowVolumeExpansion: {{ .allowVolumeExpansion }}
  {{- end }}
  {{- end }}
{{- end }}
