{{- range $nodeGroupOverrides := .Values.nodeGroups }}
{{- $nodeGroup := deepCopy $.Values.nodeGroupDefaults | mustMerge $nodeGroupOverrides }}
{{- if $nodeGroup.healthCheck.enabled }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "openstack-cluster.componentName" (list $ $nodeGroup.name) }}
  labels: {{ include "openstack-cluster.nodeGroupLabels" (list $ $nodeGroup.name) | nindent 4 }}
spec:
  clusterName: {{ include "openstack-cluster.clusterName" $ }}
  selector:
    matchLabels: {{ include "openstack-cluster.nodeGroupSelectorLabels" (list $ $nodeGroup.name) | nindent 6 }}
  {{- toYaml $nodeGroup.healthCheck.spec | nindent 2 }}
{{- end }}
{{- end }}
