{{/*
  Machine templates are immutable, so we need to make a new one when the spec changes.
  To do this, we create a new template whenever the checksum of the spec changes.
*/}}
{{- define "openstack-cluster.nodegroup.mt.spec" -}}
{{- $ctx := index . 0 }}
{{- $nodeGroup := index . 1 }}
template:
  spec:
    identityRef:
      kind: Secret
      name: {{ include "openstack-cluster.componentName" (list $ctx "cloud-config") }}
    cloudName: openstack
    image: {{ tpl (required ".Values.machineImage is required" $ctx.Values.machineImage) . }}
    flavor: {{ pluck "machineFlavor" $nodeGroup $ctx.Values.nodeGroupDefaults | first | required (printf "no flavor specified for node group '%s'" $nodeGroup.name) }}
    sshKeyName: {{ $ctx.Values.machineSSHKeyName | required ".Values.machineSSHKeyName is required" }}
{{- end }}

{{- define "openstack-cluster.nodegroup.mt.checksum" -}}
{{- include "openstack-cluster.nodegroup.mt.spec" . | sha256sum }}
{{- end }}

{{- define "openstack-cluster.nodegroup.mt.name" -}}
{{- $ctx := index . 0 }}
{{- $nodeGroup := index . 1 }}
{{- $checksum := include "openstack-cluster.nodegroup.mt.checksum" . }}
{{- include "openstack-cluster.componentName" (list $ctx $nodeGroup.name) }}-{{ trunc 8 $checksum }}
{{- end }}

{{- range $nodeGroup := .Values.nodeGroups }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstack-cluster.nodegroup.mt.name" (list $ $nodeGroup) }}
  labels: {{ include "openstack-cluster.nodeGroupLabels" (list $ $nodeGroup.name) | nindent 4 }}
  annotations:
    capi.stackhpc.com/template-checksum: {{ include "openstack-cluster.nodegroup.mt.checksum" (list $ $nodeGroup) }}
    # Ensure that the previous machine templates are kept around
    helm.sh/resource-policy: keep
spec:
  {{- include "openstack-cluster.nodegroup.mt.spec" (list $ $nodeGroup) | nindent 2 }}
{{- end }}
