{{- if and (not .Values.bootstrapOnly) .Values.customHelmReleases }}
{{- range $releaseName, $releaseSpec := .Values.customHelmReleases }}
{{- $componentName := printf "helm-%s" $releaseName }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cluster-addons.componentName" (list $ $componentName) }}-{{ $.Release.Revision }}
  labels: {{ include "cluster-addons.componentLabels" (list $ $componentName) | nindent 4 }}
spec:
  # Keep trying for a decent amount of time before failing
  backoffLimit: 1000
  # Keep succeeded jobs for 5m after finishing
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels: {{ include "cluster-addons.componentSelectorLabels" (list $ $componentName) | nindent 8 }}
    spec:
      # Ensure that we run as a non-root user
      securityContext:
        runAsUser: 1001
      serviceAccountName: {{ include "cluster-addons.componentName" (list $ "deployer") }}
      restartPolicy: OnFailure
      containers:
        - name: helm
          image: {{ printf "%s:%s" $.Values.jobImage.repository (default $.Chart.AppVersion $.Values.jobImage.tag) }}
          imagePullPolicy: {{ $.Values.jobImage.pullPolicy }}
          args:
            - helm
            - upgrade
            - {{ $releaseName }}
            - {{ $releaseSpec.chart.name }}
            - --atomic
            - --install
            - --namespace
            - {{ default $releaseName $releaseSpec.namespace }}
            - --create-namespace
            - --repo
            - {{ $releaseSpec.chart.repo }}
            - --version
            - {{ $releaseSpec.chart.version }}
            - --values
            - /config/values.yaml
            - --wait
            - --timeout
            - {{ default "5m" $releaseSpec.timeout }}
          volumeMounts:
            - name: helm-values
              mountPath: /config
              readOnly: true
      volumes:
        - name: helm-values
          secret:
            secretName: {{ include "cluster-addons.componentName" (list $ (printf "%s-values" $componentName)) }}
{{- end }}
{{- end }}
