{{- if and (not .Values.bootstrapOnly) .Values.customHelmReleases }}
{{- range $releaseName, $releaseSpec := .Values.customHelmReleases }}
{{- $componentName := printf "helm-%s" $releaseName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list $ (printf "%s-values" $componentName)) }}
  labels: {{ include "cluster-addons.componentLabels" (list $ $componentName) | nindent 4 }}
stringData:
  values.yaml: |
    {{- default dict $releaseSpec.values | toYaml | nindent 4 }}
{{- end }}
{{- end }}
