{{- if and .Values.openstack.enabled .Values.openstack.ccm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "ccm-openstack-kustomize") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "ccm-openstack") | nindent 4 }}
stringData:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
    {{- range $manifestTemplate := .Values.openstack.ccm.manifests }}
    - {{ tpl $manifestTemplate $ }}
    {{- end }}
    patches:
    {{- if semverCompare "~1.21.0" .Capabilities.KubeVersion.Version }}
    - patch: |-
        - op: add
          path: /rules/-
          value:
            apiGroups: [""]
            resources: ["serviceaccounts/token"]
            verbs: ["create"]
      target:
        group: rbac.authorization.k8s.io
        version: v1
        kind: ClusterRole
        name: system:cloud-controller-manager
    {{- end }}
    {{- with .Values.openstack.ccm.kustomization }}
    {{- with .patches }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with omit . "patches" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}
