---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-addons.fullname" . }}
  labels: {{ include "cluster-addons.labels" . | nindent 4 }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: {{ include "cluster-addons.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
