{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cluster-addons.fullname" . }}-manage-jobs
  labels: {{ include "cluster-addons.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - get
      - watch
      - patch
{{- end }}
