apiVersion: v2
name: addon
description: >
  Helm chart that provides templates for producing jobs that install addons onto a target cluster.
  The target cluster can be local (using a service account) or remote (using a kubeconfig file).
type: library
version: 0.1.0
appVersion: main
