{{- if and .Values.cni.enabled (eq .Values.cni.type "cilium") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "cni-cilium") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    image:
      repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/cilium
    certgen:
      image:
        repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/certgen
    hubble:
      relay:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/hubble-relay
      ui:
        backend:
          image:
            repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/hubble-ui-backend
        frontend:
          image:
            repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/hubble-ui
    operator:
      image:
        repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/operator
    nodeinit:
      image:
        repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/startup-script
    preflight:
      image:
        repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/cilium
    clustermesh:
      apiserver:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/cilium/clustermesh-apiserver
      etcd:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}quay.io/coreos/etcd"
  overrides: |
    {{- toYaml .Values.cni.cilium.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "cni-cilium") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.cni.cilium.chart | nindent 4 }}
  targetNamespace: {{ .Values.cni.cilium.release.namespace }}
  releaseName: cni-cilium
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
        key: overrides
{{- end }}
