apiVersion: v2
name: openstack-cluster
description: Helm chart for deploying a cluster on an OpenStack cloud using Cluster API.
type: application
version: 0.1.0
# This represents the version of the utils image to use
appVersion: "1.16.0"
