{{- if and (not .Values.bootstrapOnly) .Values.customManifests }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cluster-addons.componentName" (list . "custom-manifests") }}-{{ .Release.Revision }}
  labels: {{ include "cluster-addons.componentLabels" (list . "custom-manifests") | nindent 4 }}
spec:
  # Keep trying for a decent amount of time before failing
  backoffLimit: 1000
  # Keep succeeded jobs for 5m after finishing
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels: {{ include "cluster-addons.componentSelectorLabels" (list . "custom-manifests") | nindent 8 }}
    spec:
      # Ensure that we run as a non-root user
      securityContext:
        runAsUser: 1001
      serviceAccountName: {{ include "cluster-addons.componentName" (list . "deployer") }}
      restartPolicy: OnFailure
      containers:
        - name: custom-manifests
          image: {{ printf "%s:%s" .Values.jobImage.repository (default .Chart.AppVersion .Values.jobImage.tag) }}
          imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
          args:
            - kubectl
            - apply
            - -f
            - /manifests
          volumeMounts:
            - name: manifests
              mountPath: /manifests
              readOnly: true
      volumes:
        - name: manifests
          secret:
            secretName: {{ include "cluster-addons.componentName" (list . "custom-manifests") }}
{{- end }}
