{{- if and (not .Values.bootstrapOnly) .Values.customManifests }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "custom-manifests") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "custom-manifests") | nindent 4 }}
stringData: {{ toYaml .Values.customManifests | nindent 2 }}
{{- end }}
