{{- define "cluster-addons.cert-manager.config" -}}
{{- include "cluster-addons.job.defaults" . }}
installType: helm
helm: {{ omit .Values.certManager "enabled" "acmeHttp01Issuer" | toYaml | nindent 2 }}
{{- if and .Values.ingress.enabled .Values.certManager.acmeHttp01Issuer.enabled }}
extraFiles:
  acme-http01-issuer.yaml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: {{ .Values.certManager.acmeHttp01Issuer.name }}
    spec:
      acme:
        server: {{ .Values.certManager.acmeHttp01Issuer.server }}
        privateKeySecretRef:
          name: {{ .Values.certManager.acmeHttp01Issuer.name }}-key
        solvers:
          - http01:
              ingress:
                {{- if .Values.ingress.nginx.enabled }}
                class: {{ dig "controller" "ingressClassResource" "name" "nginx" .Values.ingress.nginx.release.values }}
                {{- else }}
                {{- fail "Ingress is enabled but no ingress controllers are enabled" }}
                {{- end }}
hooks:
  postInstall: |
    kubectl apply -f ./acme-http01-issuer.yaml
{{- end }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "cert-manager"
    "cluster-addons.cert-manager.config"
    .Values.certManager.enabled
  )
}}
