{{- define "cluster-addons.cni-weave.script" -}}
set -exo pipefail
kubernetes_vn="$(kubectl version | base64 | tr -d '\n')"
kubectl apply -f "{{ tpl .Values.cni.weave.manifestURL . }}?k8s-version=$kubernetes_vn"
kubectl -n kube-system rollout status daemonset/weave-net
{{- end }}

{{- if and .Values.cni.enabled (eq .Values.cni.type "weave") }}
{{ include "cluster-addons.job" (list . "cni-weave" (dict "cni" true)) }}
{{- end }}
