{{- define "cluster-addons.cni-calico.config" -}}
{{- include "cluster-addons.job.defaults" (list . "cni-calico") }}
installType: kustomize
kustomize:
  kustomizationTemplate: |
    resources:
      {{- range .Values.cni.calico.manifests }}
      - {{ tpl . $ }}
      {{- end }}
    patches:
      - patch: |-
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --kubelet-insecure-tls
        target:
          kind: Deployment
          name: metrics-server
  {{- with .Values.cni.calico.kustomization }}
  kustomization: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "cni-calico"
    "cluster-addons.cni-calico.config"
  )
}}
