{{- if and .Values.cni.enabled (eq .Values.cni.type "cilium") }}
{{-
  include "cluster-addons.job.helm" (list
    .
    "cni-cilium"
    .Values.cni.cilium
    (dict "bootstrap" true)
  )
}}
{{- end }}
