{{- define "cluster-addons.cni-calico.config" -}}
{{- include "cluster-addons.job.defaults" (list . "cni-calico") }}
installType: helm
helm: {{ toYaml .Values.cni.calico | nindent 2 }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "cni-calico"
    "cluster-addons.cni-calico.config"
  )
}}
