{{- define "cluster-addons.cni-cilium.config" -}}
{{- include "cluster-addons.job.defaults" . }}
installType: helm
helm: {{ toYaml .Values.cni.cilium | nindent 2 }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "cni-cilium"
    "cluster-addons.cni-cilium.config"
    (and .Values.cni.enabled (eq .Values.cni.type "cilium"))
  )
}}
