{{- define "cluster-addons.csi-cinder.config" -}}
{{- include "cluster-addons.job.defaults" (list . "csi-cinder") }}
installType: kustomize
kustomize:
  kustomizationTemplate: |
    resources:
      {{- range .Values.openstack.csiCinder.manifests }}
      - {{ tpl . $ }}
      {{- end }}
      {{- if .Values.openstack.csiCinder.storageClass.enabled }}
      - ./storageclass.yaml
      {{- end }}
  {{- with .Values.openstack.csiCinder.kustomization }}
  kustomization: {{ toYaml . | nindent 4 }}
  {{- end }}
  watches:
    - namespace: kube-system
      kind: StatefulSet
      name: csi-cinder-controllerplugin
    - namespace: kube-system
      kind: Daemonset
      name: csi-cinder-nodeplugin
{{- with .Values.openstack.csiCinder.storageClass }}
{{- if .enabled }}
extraFiles:
  storageclass.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: {{ .name }}
      {{- if .isDefault }}
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      {{- end }}
    provisioner: cinder.csi.openstack.org
    reclaimPolicy: {{ .reclaimPolicy }}
    allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- end }}
{{- end }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "csi-cinder"
    "cluster-addons.csi-cinder.config"
  )
}}
