{{- define "cluster-addons.custom-manifests.config" -}}
{{- range $fileName, $manifestTemplate := .Values.customManifests }}
{{ $fileName }}: |
  {{- tpl $manifestTemplate $ | nindent 2 }}
{{- end }}
{{- end }}

{{- define "cluster-addons.custom-manifests.script" -}}
kubectl apply -f /config
{{- end }}

{{- if .Values.customManifests }}
{{- include "cluster-addons.job" (list . "custom-manifests") }}
{{- end }}
