{{- define "cluster-addons.extra-addons.config" -}}
{{- $ctx := index . 0 }}
{{- $name := index . 1 }}
{{-
  $config := omit
    (index . 2)
    "kubeconfigSecret"
    "serviceAccountName"
    "enabled"
    "dependsOn"
    "uninstallHookWeight"
}}
{{-
  include "cluster-addons.job.defaults" (list $ctx $name) |
    fromYaml |
    merge $config |
    toYaml
}}
{{- end }}

{{- range $name, $config := .Values.extraAddons }}
---
{{- $merged := include "cluster-addons.extra-addons.config" (list $ $name $config) | fromYaml }}
{{- include "addon.job.fromConfig" (list $ $name $merged) }}
{{- end }}
