{{- define "cluster-addons.extra-addons.config" -}}
{{- $ctx := index . 0 }}
{{- $config := index . 1 }}
{{-
  include "cluster-addons.job.defaults" $ctx |
    fromYaml |
    merge $config |
    toYaml
}}
{{- end }}

{{- range $name, $config := .Values.extraAddons -}}
{{- $merged := include "cluster-addons.extra-addons.config" (list $ $config) | fromYaml }}
{{-
  include "addon.job.fromConfig" (list
    $
    $name
    (omit $merged "enabled")
    (default true $merged.enabled)
    0
  )
}}
{{- end }}
