{{- define "cluster-addons.ingress-nginx.config" -}}
{{- include "cluster-addons.job.defaults" (list . "ingress-nginx") }}
installType: helm
helm: {{ omit .Values.ingress.nginx "enabled" | toYaml | nindent 2 }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "ingress-nginx"
    "cluster-addons.ingress-nginx.config"
  )
}}
