{{- define "cluster-addons.loki-stack.config" -}}
{{- include "cluster-addons.job.defaults" (list . "loki-stack") }}
installType: helm
helm: {{ omit .Values.monitoring.lokiStack "enabled" | toYaml | nindent 2 }}
# Add a datasource to the kube-prometheus-stack Grafana
extraFiles:
  configmap-grafana-datasource.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-stack-grafana-datasource
      namespace: {{ .Values.monitoring.kubePrometheusStack.release.namespace }}
      labels:
        {{- include "cluster-addons.labels" . | nindent 8 }}
        grafana_datasource: "1"
    data:
      loki-datasource.yaml: |-
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki-stack.{{ .Values.monitoring.lokiStack.release.namespace }}:3100
            access: proxy
            version: 1
  configmap-grafana-dashboard.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-stack-grafana-dashboard
      namespace: {{ .Values.monitoring.kubePrometheusStack.release.namespace }}
      labels:
        {{- include "cluster-addons.labels" . | nindent 8 }}
        grafana_dashboard: "1"
    data:
      loki-dashboard.json: |
        {{- .Files.Get "grafana-dashboards/loki-dashboard.json" | nindent 8 }}
hooks:
  postInstall: |
    kubectl apply -f ./configmap-grafana-datasource.yaml
    kubectl apply -f ./configmap-grafana-dashboard.yaml
  preDelete: |
    kubectl delete -f ./configmap-grafana-datasource.yaml
    kubectl delete -f ./configmap-grafana-dashboard.yaml
{{- end }}

{{-
  include "addon.job" (list
    .
    "loki-stack"
    "cluster-addons.loki-stack.config"
  )
}}
