{{- define "cluster-addons.loki-stack.config" -}}
{{- include "cluster-addons.job.defaults" (list . "loki-stack") }}
installType: helm
helm: {{ omit .Values.monitoring.lokiStack "enabled" | toYaml | nindent 2 }}
# Add a datasource to the kube-prometheus-stack Grafana
extraFiles:
  configmap-grafana-datasource.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-stack-grafana-datasource
      namespace: {{ .Values.monitoring.kubePrometheusStack.release.namespace }}
      labels:
        {{- include "cluster-addons.labels" . | nindent 8 }}
        grafana_datasource: "1"
    data:
      loki-datasource.yaml: |-
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki-stack.{{ .Values.monitoring.lokiStack.release.namespace }}:3100
            access: proxy
            version: 1
  configmap-grafana-dashboard.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-stack-grafana-dashboard
      namespace: {{ .Values.monitoring.kubePrometheusStack.release.namespace }}
      labels:
        {{- include "cluster-addons.labels" . | nindent 8 }}
        grafana_dashboard: "1"
    data:
      loki-dashboard.json: |
        {
          "__requires": [
            {
              "type": "grafana",
              "id": "grafana",
              "name": "Grafana",
              "version": "6.7.0"
            },
            {
              "type": "panel",
              "id": "graph",
              "name": "Graph",
              "version": ""
            },
            {
              "type": "panel",
              "id": "logs",
              "name": "Logs",
              "version": ""
            },
            {
              "type": "datasource",
              "id": "loki",
              "name": "Loki",
              "version": "1.0.0"
            },
            {
              "type": "datasource",
              "id": "prometheus",
              "name": "Prometheus",
              "version": "1.0.0"
            },
            {
              "type": "panel",
              "id": "text",
              "name": "Text",
              "version": ""
            }
          ],
          "editable": false,
          "gnetId": null,
          "graphTooltip": 0,
          "id": null,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": true,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Loki",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": {
                "h": 3,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "hiddenSeries": false,
              "id": 6,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": false,
                "total": false,
                "values": false
              },
              "lines": false,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": {
                "dataLinks": []
              },
              "percentage": false,
              "pointradius": 2,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"[$__interval]))",
                  "refId": "A"
                }
              ],
              "thresholds": [],
              "timeFrom": null,
              "timeRegions": [],
              "timeShift": null,
              "title": "",
              "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
              },
              "yaxes": [
                {
                  "$$hashKey": "object:168",
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": false
                },
                {
                  "$$hashKey": "object:169",
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": false
                }
              ],
              "yaxis": {
                "align": false,
                "alignLevel": null
              }
            },
            {
              "datasource": "Loki",
              "gridPos": {
                "h": 25,
                "w": 24,
                "x": 0,
                "y": 3
              },
              "id": 2,
              "maxDataPoints": "",
              "options": {
                "showLabels": false,
                "showTime": true,
                "sortOrder": "Descending",
                "wrapLogMessage": true
              },
              "targets": [
                {
                  "expr": "{namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"",
                  "refId": "A"
                }
              ],
              "timeFrom": null,
              "timeShift": null,
              "title": "Logs Panel",
              "type": "logs"
            }
          ],
          "schemaVersion": 22,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": [
              {
                "allValue": null,
                "current": {},
                "datasource": "Prometheus",
                "definition": "label_values(kube_pod_info, namespace)",
                "hide": 0,
                "includeAll": false,
                "index": -1,
                "label": null,
                "multi": false,
                "name": "namespace",
                "options": [],
                "query": "label_values(kube_pod_info, namespace)",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tags": [],
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "allValue": ".*",
                "current": {},
                "datasource": "Prometheus",
                "definition": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)",
                "hide": 0,
                "includeAll": true,
                "index": -1,
                "label": null,
                "multi": true,
                "name": "pod",
                "options": [],
                "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "tagValuesQuery": "",
                "tags": [],
                "tagsQuery": "",
                "type": "query",
                "useTags": false
              },
              {
                "current": {},
                "hide": 0,
                "label": null,
                "name": "search",
                "options": [],
                "query": "",
                "skipUrlSync": false,
                "type": "textbox"
              }
            ]
          },
          "time": {
            "from": "now-30m",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ]
          },
          "timezone": "",
          "title": "Loki / Logs",
          "uid": "209fd89b771c318dd442225414a50b59",
          "variables": {
            "list": []
          },
          "version": 1,
          "description": "Search logs stored in Loki"
        }
hooks:
  postInstall: |
    kubectl apply -f ./configmap-grafana-datasource.yaml
    kubectl apply -f ./configmap-grafana-dashboard.yaml
  preDelete: |
    kubectl delete -f ./configmap-grafana-datasource.yaml
    kubectl delete -f ./configmap-grafana-dashboard.yaml
{{- end }}

{{-
  include "addon.job" (list
    .
    "loki-stack"
    "cluster-addons.loki-stack.config"
  )
}}
