{{- define "cluster-addons.metrics-server.config" -}}
{{- include "cluster-addons.job.defaults" . }}
installType: kustomize
kustomize:
  kustomizationTemplate: |
    resources:
      {{- range .Values.metricsServer.manifests }}
      - {{ tpl . $ }}
      {{- end }}
  {{- with .Values.metricsServer.kustomization }}
  kustomization: {{ toYaml . | nindent 4 }}
  {{- end }}
  watches:
    - namespace: kube-system
      kind: Deployment
      name: metrics-server
{{- end }}

{{-
  include "addon.job" (list
    .
    "metrics-server"
    "cluster-addons.metrics-server.config"
    .Values.metricsServer.enabled
    0
  )
}}
