{{- define "cluster-addons.monitoring.config" -}}
{{- include "cluster-addons.job.defaults" (list . "monitoring") }}
installType: helm
helm: {{ omit .Values.monitoring "enabled" | toYaml | nindent 2 }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "monitoring"
    "cluster-addons.monitoring.config"
  )
}}
