{{- define "cluster-addons.nvidia-gpu-operator.config" -}}
{{- include "cluster-addons.job.defaults" (list . "nvidia-gpu-operator") }}
installType: helm
helm: {{ omit .Values.nvidiaGPUOperator "enabled" | toYaml | nindent 2 }}
{{- end }}

{{-
  include "addon.job" (list
    .
    "nvidia-gpu-operator"
    "cluster-addons.nvidia-gpu-operator.config"
  )
}}
