{{- if .Values.openstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  # The namespace and name must match those expected by the manifests
  name: cloud-config
  namespace: kube-system
  labels: {{ include "cluster-addons.componentLabels" (list . "openstack") | nindent 4 }}
  # The addons helm release might be deleted without deleting the OpenStack integrations
  # So leave this behind in order for them to continue functioning
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  # Just include the data for the cloud we will be using
  clouds.yaml: |
    clouds:
      openstack:
        {{ index .Values.clouds .Values.cloudName | toYaml | indent 8 | trim }}
  # Include the certificate if specified
  {{- with .Values.cloudCACert }}
  cacert: |
    {{ . | indent 4 | trim }}
  {{- end }}
  # In the cloud.conf, reference the clouds.yaml for authentication params
  cloud.conf: |
    [Global]
    use-clouds=true
    clouds-file=/etc/config/clouds.yaml
    cloud=openstack
    {{- if .Values.cloudCACert }}
    ca-file=/etc/config/cacert
    {{- end }}

    {{- with .Values.openstack.cloudConfig }}
    {{- nindent 4 . }}
    {{- end }}
{{- end }}
