{{- if .Values.addons.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "addon-deployer") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "addons") | nindent 4 }}
{{- end }}
