apiVersion: capi.stackhpc.com/v1alpha1
kind: Addon
metadata:
  name: metrics-server
spec:
  # We can access this in the kustomization template
  # Just make sure it doesn't conflict with any actual chart options!
  version: v0.5.2
  installType: kustomize
  kustomize:
    kustomizationTemplate: |
      resources:
        - https://github.com/kubernetes-sigs/metrics-server/releases/download/{{ .Values.version }}/components.yaml
    kustomization:
      patches:
        - patch: |-
            - op: add
              path: /spec/template/spec/containers/0/args/-
              value: --kubelet-insecure-tls
          target:
            kind: Deployment
            name: metrics-server
    # Define the resources to watch for
    resourceNamespace: kube-system
    resources:
      - deployment/metrics-server
