---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackCluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.commonLabels" . | nindent 4 }}
spec:
  identityRef:
    kind: Secret
    name: {{ include "openstack-cluster.componentName" (list . "cloud-config") }}
  cloudName: openstack
  {{- with .Values.controlPlaneEndpoint }}
  controlPlaneEndpoint: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterNetworking }}
  dnsNameservers: {{ .dnsNameservers | toYaml | nindent 4 }}
  managedSecurityGroups: {{ .manageSecurityGroups }}
  allowAllInClusterTraffic: {{ .allowAllInClusterTraffic }}
  {{- with .externalNetworkID }}
  externalNetworkId: {{ . }}
  {{- end }}
  {{- with .internalNetwork }}
  {{- if or .networkFilter .subnetFilter }}
  {{- with .networkFilter }}
  network: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .subnetFilter }}
  subnet: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- else }}
  nodeCidr: {{ .nodeCidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.apiServer }}
  managedAPIServerLoadBalancer: {{ .enableLoadBalancer }}
  disableAPIServerFloatingIP: {{ not .associateFloatingIP }}
  {{- with .floatingIP }}
  apiServerFloatingIP: {{ . }}
  {{- end }}
  {{- with .fixedIP }}
  apiServerFixedIP: {{ . }}
  {{- end }}
  apiServerPort: {{ .port }}
  {{- end }}
