---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.commonLabels" . | nindent 4 }}
spec:
  clusterNetwork: {{ .Values.kubeNetwork | toYaml | nindent 4 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: OpenStackCluster
    name: {{ include "openstack-cluster.clusterName" . }}
