{{- range $nodeGroup := .Values.nodeGroups }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "openstack-cluster.componentName" (list $ $nodeGroup.name) }}
  labels: {{ include "openstack-cluster.nodeGroupLabels" (list $ $nodeGroup.name) | nindent 4 }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ "{{" }} local_hostname {{ "}}" }}'
          kubeletExtraArgs:
            cloud-provider: external
{{- end }}
