---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "cloud-config") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "cloud-config") | nindent 4 }}
stringData:
  # Just include the data for the cloud we will be using
  clouds.yaml: |
    clouds:
      {{ .Values.cloudName }}:
        {{ index .Values.clouds .Values.cloudName | toYaml | indent 8 | trim }}
  {{- with .Values.cloudCACert }}
  cacert: |
    {{ . | indent 4 | trim }}
  {{- end }}
