name: Ensure OpenStack image

description: >-
  Ensures that the specified image exists in the target OpenStack cloud.

inputs:
  os-client-config-file:
    description: The path of the OpenStack clouds file
    required: true
    default: ./clouds.yml
  os-cloud:
    description: The name of the cloud within the OpenStack clouds file
    required: true
    default: openstack
  image-name:
    description: The name of the image to use
    required: true
  image-url:
    description: The URL of the image
    required: true

outputs:
  image-id:
    description: The ID of the image
    value: ${{ steps.ensure-image.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: ensure-image
      run: ./scripts/ensure-image.sh
      shell: bash
      env:
        OS_CLIENT_CONFIG_FILE: ${{ inputs.os-client-config-file }}
        OS_CLOUD: ${{ inputs.os-cloud }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_URL: ${{ inputs.image-url }}
