{{- if and .Values.monitoring.enabled .Values.monitoring.lokiStack.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-stack") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "loki-stack") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    loki:
      image:
        repository: {{ include "cluster-addons.imagePrefix" . }}docker.io/grafana/loki
    promtail:
      image:
        registry: {{ include "cluster-addons.imagePrefix" . }}docker.io
    grafana:
      sidecar:
        datasources:
          enabled: false
  overrides: |
    {{- toYaml .Values.monitoring.lokiStack.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-stack") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "loki-stack") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.monitoring.lokiStack.chart | nindent 4 }}
  targetNamespace: {{ .Values.monitoring.lokiStack.release.namespace }}
  releaseName: loki-stack
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "loki-stack") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "loki-stack") }}-config
        key: overrides
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-stack-dashboards") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "loki-stack-dashboards") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.monitoring.kubePrometheusStack.release.namespace }}
  releaseName: loki-stack-dashboards
  manifestSources:
    - template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: loki-stack-grafana-datasource
          labels:
            grafana_datasource: "1"
        data:
          loki-datasource.yaml: |-
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                url: http://loki-stack.{{ .Values.monitoring.lokiStack.release.namespace }}:3100
                access: proxy
                version: 1
                isDefault: false
    - template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: loki-stack-grafana-dashboard
          labels:
            grafana_dashboard: "1"
        data:
          loki-dashboard.json: |
            {{- .Files.Get "grafana-dashboards/loki-dashboard.json" | nindent 12 }}
{{- end }}
