{{- if and .Values.openstack.enabled .Values.openstack.csiCinder.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cinder") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "csi-cinder") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  # By default, we disable the storage class deployed by the cinder-csi chart
  # We deploy our own instead as it gives us more control over the parameters
  defaults: |
    csi:
      attacher:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/csi-attacher
      provisioner:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/csi-provisioner
      snapshotter:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/csi-snapshotter
      resizer:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/csi-resizer
      livenessprobe:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/livenessprobe
      nodeDriverRegistrar:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/csi-node-driver-registrar
      plugin:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}docker.io/k8scloudprovider/cinder-csi-plugin
        # This has to be non-empty or the chart fails to render
        volumes:
          - name: cacert
            emptyDir: {}
        volumeMounts:
          - name: cloud-config
            mountPath: /etc/config
            readOnly: true
          - name: cloud-config
            mountPath: /etc/kubernetes
            readOnly: true
      snapshotController:
        image:
          repository: {{ include "cluster-addons.imagePrefix" . }}k8s.gcr.io/sig-storage/snapshot-controller
    secret:
      enabled: true
      create: false
      name: cloud-config
    storageClass:
      enabled: false
    clusterID: {{ include "cluster-addons.clusterName" . }}
  overrides: |
    {{- toYaml .Values.openstack.csiCinder.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cinder") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "csi-cinder") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.openstack.csiCinder.chart | nindent 4 }}
  targetNamespace: {{ .Values.openstack.targetNamespace }}
  releaseName: csi-cinder
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "csi-cinder") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "csi-cinder") }}-config
        key: overrides
{{- if .Values.openstack.csiCinder.storageClass.enabled }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cinder-storageclass") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "csi-cinder-storageclass") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.openstack.targetNamespace }}
  releaseName: csi-cinder-storageclass
  manifestSources:
    - template: |
        {{- with .Values.openstack.csiCinder.storageClass }}
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: {{ .name }}
          {{- if .isDefault }}
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          {{- end }}
        provisioner: cinder.csi.openstack.org
        parameters:
          availability: {{ .availabilityZone }}
          {{- with .volumeType }}
          type: {{ . }}
          {{- end }}
        reclaimPolicy: {{ .reclaimPolicy }}
        allowVolumeExpansion: {{ .allowVolumeExpansion }}
        volumeBindingMode: WaitForFirstConsumer
        {{- with .allowedTopologies }}
        allowedTopologies: {{ toYaml . | nindent 6 }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
