name: Ensure CAPI images
on:
  workflow_call:
    outputs:
      kube-1-25-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-25-image }}
      kube-1-25-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-25-version }}
      kube-1-26-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-26-image }}
      kube-1-26-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-26-version }}
      kube-1-27-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-27-image }}
      kube-1-27-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-27-version }}

jobs:
  get_image_manifest:
    runs-on: ubuntu-latest
    outputs: ${{ fromJSON(steps.images.outputs.manifest) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch image details
        id: images
        run: |
          VN="$(jq -r '.["azimuth-images"]' ./dependencies.json)"
          MANIFEST="$(curl -fsSL "https://github.com/stackhpc/azimuth-images/releases/download/${VN}/manifest.json")"
          echo "manifest=$(jq -c . <<< "$MANIFEST")" >> $GITHUB_OUTPUT

  debug_manifest:
    runs-on: ubuntu-latest
    needs: [get_image_manifest]
    steps:
      - uses: DamianReeves/write-file-action@master
        with:
          path: manifest.json
          write-mode: overwrite
          contents: ${{ needs.get_image_manifest.outputs }}


  # ensure-capi-images:
  #   runs-on: ubuntu-latest
  #   # We output the image IDs for each image
  #   outputs:
  #     kube-1-25-image: ${{ steps.kube-1-25.outputs.image-id }}
  #     kube-1-25-version: 1.25.10
  #     kube-1-26-image: ${{ steps.kube-1-26.outputs.image-id }}
  #     kube-1-26-version: 1.26.5
  #     kube-1-27-image: ${{ steps.kube-1-27.outputs.image-id }}
  #     kube-1-27-version: 1.27.2
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Read dependencies
  #       id: deps
  #       run: ./scripts/read-dependencies.sh

  #     - name: Write cloud credential
  #       run: >
  #         echo "$CLOUD" > clouds.yml
  #       shell: bash
  #       env:
  #         CLOUD: ${{ secrets.CLOUD }}

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #         check-latest: true

  #     - name: Install OpenStack CLI
  #       run: pip install python-openstackclient

  #     - name: Ensure Kubernetes 1.25 image
  #       id: kube-1-25
  #       uses: ./.github/actions/ensure-image
  #       with:
  #         image-name: ubuntu-focal-kube-v1.25.10-230602-1732
  #       if: ${{ !github.event.pull_request.draft }}

  #     - name: Ensure Kubernetes 1.26 image
  #       id: kube-1-26
  #       uses: ./.github/actions/ensure-image
  #       with:
  #         image-name: ubuntu-focal-kube-v1.26.5-230602-1757
  #       if: ${{ !github.event.pull_request.draft }}

  #     - name: Ensure Kubernetes 1.27 image
  #       id: kube-1-27
  #       uses: ./.github/actions/ensure-image
  #       with:
  #         image-name: ubuntu-focal-kube-v1.27.2-230602-1824
