name: Ensure CAPI images
on:
  workflow_call:
    outputs:
      kube-1-25-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-25-image }}
      kube-1-25-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-25-version }}
      kube-1-26-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-26-image }}
      kube-1-26-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-26-version }}
      kube-1-27-image:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-27-image }}
      kube-1-27-version:
        value: ${{ jobs.ensure-capi-images.outputs.kube-1-27-version }}

jobs:
  image_manifest:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.images.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch image details
        id: images
        run: |
          VN="$(jq -r '.["azimuth-images"]' ./dependencies.json)"
          MANIFEST="$(curl -fsSL "https://github.com/stackhpc/azimuth-images/releases/download/${VN}/manifest.json")"
          echo "manifest=$(jq -c . <<< "$MANIFEST")" >> $GITHUB_OUTPUT

  ensure_capi_images:
    runs-on: ubuntu-latest
    needs: [image_manifest]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: kubernetes-1-25
            image-name: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-25-jammy.name }}
            image-url: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-25-jammy.url }}
            kubernetes-version: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-25-jammy.kubernetes_version }}
            skip: ${{ github.event.pull_request.draft }}
          - name: kubernetes-1-26
            image-name: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-26-jammy.name }}
            image-url: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-26-jammy.url }}
            kubernetes-version: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-26-jammy.kubernetes_version }}
            skip: ${{ github.event.pull_request.draft }}
          - name: kubernetes-1-27
            image-name: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-27-jammy.name }}
            image-url: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-27-jammy.url }}
            kubernetes-version: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-27-jammy.kubernetes_version }}
            skip: false

    # steps:
    #   - uses: DamianReeves/write-file-action@master
    #     with:
    #       path: manifest.json
    #       write-mode: overwrite
    #       contents: ${{ needs.get_image_manifest.outputs.manifest }}

    #   - run: cat manifest.json


    # outputs:
    #   kube-1-25-image: ${{ steps.kube-1-25.outputs.image-id }}
    #   kube-1-25-version: 1.25.10
    #   kube-1-26-image: ${{ steps.kube-1-26.outputs.image-id }}
    #   kube-1-26-version: 1.26.5
    #   kube-1-27-image: ${{ steps.kube-1-27.outputs.image-id }}
    #   kube-1-27-version: 1.27.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ !matrix.skip }}

      - name: Write cloud credential
        run: >
          echo "$CLOUD" > clouds.yml
        shell: bash
        env:
          CLOUD: ${{ secrets.CLOUD }}
        if: ${{ !matrix.skip }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
        if: ${{ !matrix.skip }}

      - name: Install OpenStack CLI
        run: pip install python-openstackclient
        if: ${{ !matrix.skip }}

      - name: Ensure Kubernetes image
        id: ensure-image
        uses: ./.github/actions/ensure-image
        with:
          image-name: ${{ matrix.image-name }}
          image-url: ${{ matrix.image-url }}
        if: ${{ !matrix.skip }}

      - name: Write matrix outputs
        uses: cloudposse/github-action-matrix-outputs-write@main
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.name }}
          outputs: |-
            image-id: ${{ steps.ensure-image.outputs.image-id }}
            kubernetes-version: ${{ matrix.kubernetes-version }}
        if: ${{ !matrix.skip }}

  debug_manifest:
    runs-on: ubuntu-latest
    needs: [ensure_capi_images]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read matrix outputs
        id: matrix-outputs
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: ensure_capi_images

      - name: Write outputs
        uses: DamianReeves/write-file-action@master
        with:
          path: outputs.json
          write-mode: overwrite
          contents: ${{ steps.matrix-outputs.outputs.result }}

      - run: cat outputs.json
