name: Install Helm Charts
on: [workflow_call]

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
          
      - name: Set up chart-testing
        uses: scrungus/chart-testing-action@v3.7.3
      
      - name: Copy cloud creds to file
        run: 'echo "$TYLER_CLOUDS" > clouds.yml'
        shell: bash
        env:
          TYLER_CLOUDS: ${{ secrets.TYLER_CLOUDS }}
      
      - name: Run Helm Install
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --all --helm-extra-args "-f clouds.yml --timeout 5s"