name: test main
on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/include/lint.yaml

  ensure_capi_images:
    needs: [lint]
    uses: ./.github/workflows/include/ensure-capi-images.yaml
    secrets: inherit

  test:
    needs: [ensure_capi_images]
    uses: ./.github/workflows/include/test.yaml
    secrets: inherit
    with:
      # Pass the images as JSON
      images: ${{ toJSON(needs.ensure_capi_images.outputs) }}
      # Only run the smoke tests on main
      tests-full: false
