name: test main
on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    environment: ci
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      ref-under-test: ${{ github.sha }}
      # Only run the sanity check on main
      tests-full: false
