name: test pr
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main
      - feature/ci-external-repos

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    # Using an environment means that workflow runs need to be approved
    environment: ci
    uses: ./.github/workflows/test.yaml
    with:
      ref-under-test: ${{ github.event.pull_request.head.sha }}
      # If the PR is in draft, just run a sanity check
      # If the PR is in review, run the full test suite
      tests-full: ${{ !github.event.pull_request.draft }}
