name: test pr
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main
      - feature/ci-external-repos

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Reusable workflows cannot be used with environments
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
  # So we must use a different mechanism for approvals
  wait_for_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: stackhpc/github-actions/workflow-approve@master
        with:
          approvers: mkjpryor

  lint:
    needs: [wait_for_approval]
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: cat ./.github/workflows/pr.yaml

  # test:
  #   needs: [lint]
  #   # Using an environment means that workflow runs need to be approved
  #   environment: ci
  #   uses: ./.github/workflows/test.yaml
  #   with:
  #     ref-under-test: ${{ github.event.pull_request.head.sha }}
  #     # If the PR is in draft, just run a sanity check
  #     # If the PR is in review, run the full test suite
  #     tests-full: ${{ !github.event.pull_request.draft }}
