name: test pr
on:
  pull_request:
    types: [opened,synchronize,ready_for_review,edited,reopened]
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Run the lint on every PR, even from external repos
  lint:
    uses: ./.github/workflows/lint.yaml

  # Only run image sync and test on the main repo
  sync_images:
    needs: [lint]
    uses: ./.github/workflows/sync-images.yaml
    secrets: inherit
    if: github.repository == 'stackhpc/capi-helm-charts'

  ensure_capi_images:
    needs: [lint]
    uses: ./.github/workflows/ensure-capi-images.yaml
    secrets: inherit
    if: github.repository == 'stackhpc/capi-helm-charts'

  test-kube-1-24:
    needs: [sync_images, ensure_capi_images]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      name: kube-1-24
      image: ${{ needs.ensure_capi_images.outputs.kube-1-24-image }}
      version: ${{ needs.ensure_capi_images.outputs.kube-1-24-version }}
      upgrade-image: ${{ needs.ensure_capi_images.outputs.kube-1-25-image }}
      upgrade-version: ${{ needs.ensure_capi_images.outputs.kube-1-25-version }}
    if: >-
      ${{
        github.repository == 'stackhpc/capi-helm-charts' &&
        !github.event.pull_request.draft
      }}

  test-kube-1-25:
    needs: [sync_images, ensure_capi_images]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      name: kube-1-25
      image: ${{ needs.ensure_capi_images.outputs.kube-1-25-image }}
      version: ${{ needs.ensure_capi_images.outputs.kube-1-25-version }}
      upgrade-image: ${{ needs.ensure_capi_images.outputs.kube-1-26-image }}
      upgrade-version: ${{ needs.ensure_capi_images.outputs.kube-1-26-version }}
    if: >-
      ${{
        github.repository == 'stackhpc/capi-helm-charts' &&
        !github.event.pull_request.draft
      }}

  test-kube-1-26:
    needs: [sync_images, ensure_capi_images]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      name: kube-1-26
      image: ${{ needs.ensure_capi_images.outputs.kube-1-26-image }}
      version: ${{ needs.ensure_capi_images.outputs.kube-1-26-version }}
      upgrade-image: ${{ needs.ensure_capi_images.outputs.kube-1-27-image }}
      upgrade-version: ${{ needs.ensure_capi_images.outputs.kube-1-27-version }}
    if: >-
      ${{
        github.repository == 'stackhpc/capi-helm-charts' &&
        !github.event.pull_request.draft
      }}

  test-kube-1-27:
    needs: [sync_images, ensure_capi_images]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      name: kube-1-27
      image: ${{ needs.ensure_capi_images.outputs.kube-1-27-image }}
      version: ${{ needs.ensure_capi_images.outputs.kube-1-27-version }}
    if: ${{ github.repository == 'stackhpc/capi-helm-charts' }}
