name: test pr
on:
  pull_request:
    types: [opened,synchronize,ready_for_review,edited,reopened]
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Run the lint on every PR, even from external repos
  lint:
    uses: ./.github/workflows/lint.yaml

  # Only run image sync and test on the main repo
  sync_images:
    needs: [lint]
    uses: ./.github/workflows/sync-images.yaml
    secrets: inherit
    if: github.repository == 'stackhpc/capi-helm-charts'

  ensure_capi_images:
    needs: [lint]
    uses: ./.github/workflows/ensure-capi-images.yaml
    secrets: inherit
    if: github.repository == 'stackhpc/capi-helm-charts'

  test:
    needs: [sync_images, ensure_capi_images]
    uses: ./.github/workflows/test-matrix.yaml
    secrets: inherit
    with:
      kube-1-24-image: ${{ needs.ensure_capi_images.outputs.kube-1-24-image }}
      kube-1-24-version: ${{ needs.ensure_capi_images.outputs.kube-1-24-version }}
      kube-1-25-image: ${{ needs.ensure_capi_images.outputs.kube-1-25-image }}
      kube-1-25-version: ${{ needs.ensure_capi_images.outputs.kube-1-25-version }}
      kube-1-26-image: ${{ needs.ensure_capi_images.outputs.kube-1-26-image }}
      kube-1-26-version: ${{ needs.ensure_capi_images.outputs.kube-1-26-version }}
      kube-1-27-image: ${{ needs.ensure_capi_images.outputs.kube-1-27-image }}
      kube-1-27-version: ${{ needs.ensure_capi_images.outputs.kube-1-27-version }}
    if: github.repository == 'stackhpc/capi-helm-charts'
