name: Publish dependencies on release
on:
  push:
    tags:
      - "**"

jobs:
  mirror_container_images:
    uses: ./.github/workflows/sync-images.yaml
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  publish_charts:
    uses: ./.github/workflows/publish-charts.yaml
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  publish_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Publish manifest to release
        uses: softprops/action-gh-release@v1
        with:
          files: dependencies.json
