name: Test OpenStack cluster matrix
on:
  workflow_call:
    inputs:
      kube-1-24-image:
        type: string
        required: false
      kube-1-24-version:
        type: string
        required: false
      kube-1-25-image:
        type: string
        required: false
      kube-1-25-version:
        type: string
        required: false
      kube-1-26-image:
        type: string
        required: false
      kube-1-26-version:
        type: string
        required: false
      kube-1-27-image:
        type: string
        required: true
      kube-1-27-version:
        type: string
        required: true

env:
  HELM_VERSION: v3.11.3
  CAPI_VERSION: v1.4.3
  CAPO_VERSION: v0.7.3
  ADDON_PROVIDER_VERSION: 0.1.0-dev.0.main.26
  SONOBUOY_VERSION: 0.56.16
  CERTMANAGER_VERSION: v1.12.1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: kube-1-24
            image: ${{ inputs.kube-1-24-image }}
            version: ${{ inputs.kube-1-24-version }}
            upgrade-image: ${{ inputs.kube-1-25-image }}
            upgrade-version: ${{ inputs.kube-1-25-version }}
            should-run: ${{ !github.event.pull_request.draft }}
          - name: kube-1-25
            image: ${{ inputs.kube-1-25-image }}
            version: ${{ inputs.kube-1-25-version }}
            upgrade-image: ${{ inputs.kube-1-26-image }}
            upgrade-version: ${{ inputs.kube-1-26-version }}
            should-run: ${{ !github.event.pull_request.draft }}
          - name: kube-1-26
            image: ${{ inputs.kube-1-26-image }}
            version: ${{ inputs.kube-1-26-version }}
            upgrade-image: ${{ inputs.kube-1-27-image }}
            upgrade-version: ${{ inputs.kube-1-27-version }}
            should-run: ${{ !github.event.pull_request.draft }}
          - name: kube-1-27
            image: ${{ inputs.kube-1-27-image }}
            version: ${{ inputs.kube-1-27-version }}
            should-run: true
      max-parallel: 1
      fail-fast: false
    steps:
      - uses: ./.github/workflows/test.yaml
        secrets: inherit
        if: ${{ matrix.should-run }}
        with:
          name: ${{ matrix.name }}
          image: ${{ matrix.image }}
          version: ${{ matrix.version }}
          upgrade-image: ${{ matrix.upgrade-image }}
          upgrade-version: ${{ matrix.upgrade-version }}
